$(function () {


 function update_mess () {
          loop = true;
          uri = $('#display_mess');
          selector = $('[name="visited"]');
          selector = selector.val();
          uri = uri.find('li.message');
          uri = uri.last();
          uri = uri.attr('id');
          $.post('/php_files/org_mess.php',{'convo':selector,'newer':uri},function (data) {
               html = '';
               $.each(data,function (user,conv) {
               if (loop == true) {
               loop = false;
                    html += '<li class="message" id="' + conv.messid + '"><ul class="message-content">' +
                '<li class="mess_head">' + conv.fromuser + ':</li><li class="mess_bod">' + 
                conv.message + '</li></ul></li>';
                     

               }
               });
               var oj = $('#display_mess')
               if (oj.scrollTop() + oj.innerHeight() >= oj[0].scrollHeight && loop == false) {
                    
                    var bizzle = true;
               }
               oj.append(html);
               if (bizzle == true ) {
                    oj.animate({scrollTop: oj[0].scrollHeight});
               }
                    },"json").error(function () {
                    });
          
          
          }

          function update_log () {
           $.post('/php_files/update_mess_sess.php',function (data) {
                    $.each(data,function (user,content) {
                         if (curruser == content.fromuser) {
                    otherp = content.touser;
               }
               else {
                    otherp = content.fromuser;
               }
                         selector = $('#friend_list').find('li[name=' + otherp + ']').find('.status');
                         if (content.online == null) {
                              selector.attr('class','status off_status');
                         }
                         else {
                              selector.attr('class','status on_status');
                         }
                    });
           },'json');
      }

           $('#messages').livequery (function () {
     $(this).click(function () {
     $('.chat').show();
     $('head').prepend(
     "<style id=\"dyn\"type=\"text/css\"> \
      .mess_is { \
	-moz-box-shadow:inset 0px 1px 0px 0px #ffffff; \
	-webkit-box-shadow:inset 0px 1px 0px 0px #ffffff; \
	box-shadow:inset 0px 1px 0px 0px #ffffff; \
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ededed), color-stop(1, #dfdfdf) ); \
	background:-moz-linear-gradient( center top, #ededed 5%, #dfdfdf 100% ); \
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ededed', endColorstr='#dfdfdf'); \
	background-color:#ededed; \
	-moz-border-radius:6px; \
	-webkit-border-radius:6px; \
	border-radius:6px; \
	border:1px solid #dcdcdc; \
	display:inline-block; \
	color:#777777; \
	font-family:arial; \
	font-size:15px; \
	font-weight:bold; \
	padding:6px 24px; \
	text-decoration:none; \
	text-shadow:1px 1px 0px #ffffff; margin-top: 72px;position: absolute; \
}.mess_is:hover { \
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #dfdfdf), color-stop(1, #ededed) ); \
	background:-moz-linear-gradient( center top, #dfdfdf 5%, #ededed 100% ); \
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#dfdfdf', endColorstr='#ededed'); \
	background-color:#dfdfdf; \
}.mess_is:active { \
	position:relative; \
	top:1px; \
} \
/* This imageless css button was generated by CSSButtonGenerator.com */ \
form.mess_tas { \
     background-color: rgb(247, 247, 247) !important; \
     border-radius: 0px 0px 5px 5px !important; \
} \
</style>");
     
     
          selector = $('#messages').find('img');
          selector.attr({src:img4.src});
          
          selector = $('#profile').find('img');
          selector.attr({src:img.src});
          selector = $('#contacts').find('img');
          selector.attr({src:img5.src});
          
              
          $('#messages').css({'color':'#2774b8'});
          $("a").not('[id="messages"]').css({'color':'#A8A8A8'});    

          $.post('/php_files/show_messages.php',function (data) {
                selector = $('#friend_list');
          html = '';
               $.each(data,function(user,content) {
               
               if (curruser == content.fromuser) {
                    otherp = content.touser;
               }
               else {
                    otherp = content.fromuser;
               }
               html += '<li class="show_content" name="' + otherp + 
               '"><a href="/profile/' + otherp + '.php"><img src="';
                  if (content.thumbnail != null) {
                   html += content.thumbnail;
                   }
                   else {
                   html += img.src;
                   }
                   html += '" style="height: 40px;width: 40px;float:left;"></a>' 
                  + 
                otherp + '<img class="status ';
                if (content.online == null) {
                     html += 'off_status';
                }
                else {
                     html += 'on_status';
                }
                html += '" /></li><br>';
               }); 
               selector.html(html);
               logg = window.setInterval(function () {update_log()},2000);
          },"json").error(function (data) {
          $(this).html('hi');
          
          });
          
         
     });
     



     });

        $('.show_content').livequery("click",function () {
          
          
          var id = $(this).attr('name');
          $.post('/php_files/org_mess.php',{'convo':id},function (data) {
           if (typeof upd != 'undefined') {
               clearInterval(upd);
          }
          $('#chat_name').html(id);
           $('#display_mess').empty();
           html = '';
           var thumb; 
           
     var mydate=new Date()
     var year=mydate.getYear()
    
     if (year < 1000)
         year+=1900
    
     var day=mydate.getDay()
     var n=mydate.getMonth()+1

     var daym=mydate.getDate()
     if (daym<10)
        daym="0"+daym
     var month=new Array();
     month[00]="January";
     month[01]="February";
     month[02]="March";
     month[03]="April";
     month[04]="May";
     month[05]="June";
     month[06]="July";
     month[07]="August";
     month[08]="September";
     month[09]="October";
     month[10]="November";
     month[11]="December";
     n = month[mydate.getMonth()];
    var string = n+" "+daym+" "+year;
    loop = true;
               $.each(data,function (user,conv) {
                
                thumb = conv.thumbnail;
                
                html += '<li class="message" id="' + conv.messid + '"><ul class="message-content">' +
                '<li class="mess_head">';
               if (conv.fromuser != curruser) {
                    $('li#' + conv.messid ).find('mess_head').css({
                         'color' : '#2774b8'
                    });
               }
               html += conv.fromuser + ':<span style="float: right;">' +  conv.timesent 
               + '</span></li><li class="mess_bod">' + 
               conv.message + '</li></ul></li>';
               });
               $('#chat_pic').attr({ 'src': thumb});
               $('#display_mess').html(html);        
               $('#display_mess')
               $('#mess_text').html('<form class="mess_tas" id="mess_ta"><textarea id="mess_tx" name="message" cols="30" rows="3" maxlength="2000"></textarea>' +
               '<input type="hidden" name="visited" value="' + id + '"/></form>');     
               upd = window.setInterval(function () {update_mess()},2000);
               $('#display_mess').scrollTop($('#display_mess').get(0).scrollHeight);
               },'json');
               
               
              
     });
     $('#close').livequery('click',function () {
     $('.chat').hide();
                    if (typeof upd != 'undefined') {
               clearInterval(upd);
               clearInterval(logg);
          }     
          
     });

        $('#mess_tx').livequery(function () {
          
          $("#mess_tx").keypress(function(e) {
    if(e.which == 13) {
        

        if ($('#mess_tx').val() != '') {
          uri = $('#mess_ta').serialize();
          
               $.post('/php_files/message_process.php',uri,function () {
               $('#mess_tx').val('');
                    
               });
               }
    }
          
              
          });
          });

          $('#message').livequery(function () {
          if ($(this).attr('src') != img4.src && typeof upd != 'undefined') {
               clearInterval(upd);
          }     
          });

          


})
